# 📦 개발용 Docker Compose 설정 (Vue + Express)
# - 네트워크 역할 분리
# - 마운트 및 설정파일 구조화
# - 정적/동적 요청 분기 고려 (개발 단계에선 프록시 활용)

# 운영/배포용: node:lts-alpine (단, 바이너리 빌드 시 주의 필요)
version: "3.8"

services:
  backend:
    image: node:lts
    container_name: dev_backend
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    command: sh -c "npm install && npm run dev"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      NODE_ENV: development

  frontend:
    image: node:lts
    container_name: dev_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    environment:
      VITE_API_BASE_URL: http://localhost:5000
    depends_on:
      - backend